apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-data-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-data-service
  template:
    metadata:
      labels:
        app: employee-data-service
    spec:
      containers:
        - name: employee-data-service-container
          image: asia-south1-docker.pkg.dev/niveustraining/dhanya-demo/projects:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: "EmployeeDataService"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://localhost:5432/employee_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
              value: "DEBUG"
