# Use a base image with OpenJDK 17 installed
FROM openjdk:17-jdk
EXPOSE 8080
ADD target/EmployeeDataService-0.0.1-SNAPSHOT.jar EmployeeDataService-0.0.1-SNAPSHOT.jar
ENTRYPOINT "java", "-jar", "EmployeeDataService-0.0.1-SNAPSHOT.jar"]



